# Generated by Django 4.2.3 on 2023-08-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("works", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="work",
            old_name="publish",
            new_name="is_published",
        ),
        migrations.AddField(
            model_name="work",
            name="is_casestudy",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="work",
            name="is_favouraite",
            field=models.BooleanField(default=False),
        ),
    ]
