# Generated by Django 4.2.3 on 2023-08-02 16:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("works", "0002_rename_publish_work_is_published_work_is_casestudy_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="work",
            old_name="created_on",
            new_name="createdOn",
        ),
        migrations.RenameField(
            model_name="work",
            old_name="is_casestudy",
            new_name="isCaseStudy",
        ),
        migrations.RenameField(
            model_name="work",
            old_name="is_favouraite",
            new_name="isFavouraite",
        ),
        migrations.RenameField(
            model_name="work",
            old_name="is_published",
            new_name="isPublished",
        ),
        migrations.RenameField(
            model_name="work",
            old_name="modified_on",
            new_name="modifiedOn",
        ),
        migrations.RenameField(
            model_name="work",
            old_name="published_date",
            new_name="publishedDate",
        ),
    ]
