# Generated by Django 4.2.3 on 2023-08-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("works", "0003_rename_created_on_work_createdon_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="importanceScore",
            field=models.IntegerField(default=1),
        ),
    ]
