# Generated by Django 4.2.3 on 2023-08-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("works", "0004_work_importancescore"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="views",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
