# Generated by Django 4.2.3 on 2023-08-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("works", "0006_work_heroimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="linkToCode",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="work",
            name="linkToDeployment",
            field=models.URLField(blank=True, null=True),
        ),
    ]
